### ISSUE TITLE
Script does not download mp3 anymore 

### ISSUE THREAD

**Issue by shabahmd** [exyezed/cobalt-tools#1]
It just shows a red error sign instead of green tick 
![image](https://github.com/user-attachments/assets/d57e8d61-bc99-42d3-8816-6ecc769afb59)

**Comment by exyezed** [comment]
because there is an issue with the API, I removed it and instead you can use [this,](https://greasyfork.org/en/scripts/515230-cobalt-tools-youtube-direct-downloader) it is more complete.
